plugins {
    id "com.android.application"
}

android {
    namespace "com.damitheswitch.myschedule"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.damitheswitch.myschedule"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "1.1.0"
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.14.0"
}
