plugins {
    id "com.android.application"
}

android {
    namespace "com.damitheswitch.kebiao"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.damitheswitch.kebiao"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "2.0.0"
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.14.0"
}
